### ISSUE TITLE
Add a unit tests for Command.Run

### ISSUE THREAD

**Issue by dlespiau** [clearcontainers/tests#6] opened 2017-05-05 16:46 UTC
This function has a few modes of operation. It can timeout for instance. Ensure we cover it.

**Comment by egernst** [comment] 2017-08-24 17:37
@chavafg - this is done already, right?

**Comment by egernst** [comment] 2017-08-24 17:45
duplicate of https://github.com/clearcontainers/runtime/issues/397

**Closed by egernst** 2017-08-24 17:45 UTC
