### ISSUE TITLE
checkcommits: Dont check for `Fixes #XXX`  for 'release:' commits

### ISSUE THREAD

**Issue by jcvenegas** [clearcontainers/tests#823] opened 2018-01-08 06:32 UTC
To automate more the release process is need to automatically create PRs with a version update in Clear Containers Repositories.
If a new PR is done and the commit message has the format:
`release: Message ` dont check for `Fixes`

**Comment by jcvenegas** [comment] 2018-01-08 06:32
See: 
https://github.com/clearcontainers/packaging/issues/236

**Comment by jodh-intel** [comment] 2018-01-08 12:41
Closing as this is a duplicate of #820.

**Closed by jodh-intel** 2018-01-08 12:41 UTC
